"""
Seed Ghost's memory DB with known LLM mistake patterns.

Each mistake is stored as an individual memory entry with type='mistake'
so Ghost can query relevant mistakes via memory_search(type_filter='mistake')
instead of loading all mistakes into context at once.

Run once: python seed_mistakes_memory.py
Re-running is safe — duplicates are skipped via source_hash.
"""

from ghost_memory import MemoryDB

MISTAKES = [
    {
        "id": "M-01",
        "category": "security,pipeline",
        "content": (
            "M-01 SECURITY: Never bypass the evolution pipeline. "
            "Do NOT use file_write or shell_exec with redirects (>, >>, tee) to modify Ghost's own codebase. "
            "ALL self-modification MUST go through evolve_plan -> evolve_apply -> evolve_test -> evolve_deploy. "
            "LLMs will take shortcuts if guardrails don't exist — the guardrails are there for a reason."
        ),
    },
    {
        "id": "M-02",
        "category": "security,pipeline",
        "content": (
            "M-02 SECURITY: All write vectors to Ghost's codebase are guarded. "
            "If file_write is blocked, do NOT try shell_exec with echo/tee/heredocs as a workaround. "
            "The guards cover >, >>, tee, cp, mv, and heredocs targeting the project directory. "
            "When one path is blocked, use the evolution pipeline — don't explore alternatives."
        ),
    },
    {
        "id": "M-03",
        "category": "json,evolution,large-file",
        "content": (
            "M-03 JSON: Large file contents in evolve_apply can cause JSON parse failures. "
            "When writing a new file >5KB, break it into chunks using evolve_apply_append or "
            "multiple evolve_apply calls with patches. Never cram large content into a single tool call."
        ),
    },
    {
        "id": "M-04",
        "category": "json,evolution,large-file",
        "content": (
            "M-04 JSON: Fallback shell_exec for large file writes also fails with JSON parse errors. "
            "When a tool call fails due to content size, decompose the file into smaller chunks. "
            "The evolution pipeline supports evolve_apply_append for incremental file writing."
        ),
    },
    {
        "id": "M-05",
        "category": "evolution,scope",
        "content": (
            "M-05 SCOPE: Never combine unrelated changes in a single evolution. "
            "One evolution = one focused feature. Do not simultaneously add API endpoints AND improve testing. "
            "Complex multi-scope evolutions lead to 50+ step error-riddled processes. "
            "If your plan touches more than 6 files, split into multiple features."
        ),
    },
    {
        "id": "M-06",
        "category": "python,import,bug",
        "content": (
            "M-06 PYTHON IMPORT BUG: Never use 'from module import mutable_variable'. "
            "In Python, 'from module import var' copies the value at import time. "
            "If the module later updates that variable, the importing file's copy stays stale forever. "
            "WRONG: from some_module import _shared_state (stays None forever). "
            "RIGHT: import some_module; then use some_module._shared_state (live reference). "
            "This applies to ALL mutable module-level state: processes, flags, lists, dicts."
        ),
    },
    {
        "id": "M-07",
        "category": "python,string,bug",
        "content": (
            "M-07 PYTHON STRING BUG: Never double-escape newlines in string joins. "
            "WRONG: '\\\\n'.join(lines) — inserts literal backslash-n characters. "
            "RIGHT: '\\n'.join(lines) — inserts actual newline characters. "
            "LLMs sometimes over-escape strings when generating code embedded in other strings."
        ),
    },
    {
        "id": "M-08",
        "category": "ui,modal,css",
        "content": (
            "M-08 UI: Never set display:flex on modal overlays. "
            "Modals must start hidden using style='display:none' or a CSS class like 'hidden'. "
            "Setting display:flex inline overrides the hidden class, making the modal visible on page load. "
            "Always test that modals are hidden by default."
        ),
    },
    {
        "id": "M-09",
        "category": "ui,modal,ux",
        "content": (
            "M-09 UI: Every modal MUST be dismissable via three mechanisms: "
            "(1) click handler on X/close button, (2) click handler on overlay background, "
            "(3) Escape key listener. Missing any of these traps the user in the modal. "
            "Standard UI patterns are not reliably generated by LLMs unless explicitly prompted."
        ),
    },
    {
        "id": "M-10",
        "category": "ui,form,ux",
        "content": (
            "M-10 UI: Form labels must match user-visible concepts, not internal IDs. "
            "If a label says 'Skills' but the placeholder suggests tool names like 'shell_exec, file_write', "
            "users get confused. LLMs blur distinctions between related concepts (skills vs tools)."
        ),
    },
    {
        "id": "M-11",
        "category": "ui,form,ux",
        "content": (
            "M-11 UI: Use pickers/dropdowns for known value sets, never raw text inputs. "
            "When valid inputs are known (skills, tools, providers), use a dropdown, autocomplete, "
            "or chip selector. Users don't memorize internal skill IDs. "
            "LLMs default to the simplest input (text field) rather than the most usable one."
        ),
    },
    {
        "id": "M-12",
        "category": "ui,design-system,consistency",
        "content": (
            "M-12 UI: Match the existing design system — never use emoji in Ghost dashboard. "
            "Every page uses SVG icons and colored dots. Check existing pages for patterns before creating new UI. "
            "Use CSS classes: stat-card, btn, form-input, badge, evo-tab. "
            "LLMs don't maintain visual consistency across files unless the design system is explicitly referenced."
        ),
    },
    {
        "id": "M-13",
        "category": "backend,data,scan",
        "content": (
            "M-13 BACKEND: Never rebuild state from scratch in scan/sync functions. "
            "scan() must MERGE with existing data, not replace it. "
            "If a user created an entry at a custom path, a scan that only checks hardcoded directories "
            "will silently delete it. Always preserve entries not found in the scan. "
            "Use incremental sync patterns, not clean-slate rebuilds."
        ),
    },
    {
        "id": "M-14",
        "category": "backend,api,data-loss",
        "content": (
            "M-14 BACKEND: Persist ALL request payload fields, not just some. "
            "When a POST/PUT endpoint accepts fields (e.g. skills, disabled_skills), "
            "every field must be saved to storage. Parsing input without persisting it is silent data loss. "
            "LLMs sometimes implement the 'accept' side of an API without completing the 'persist' side."
        ),
    },
    {
        "id": "M-15",
        "category": "backend,integration,wiring",
        "content": (
            "M-15 BACKEND: Wire features into the runtime, not just CRUD + UI. "
            "A feature is NOT done when the API and UI work. It's done when the runtime USES it. "
            "Example: a Projects feature must modify chat.py's _process_message to apply project context. "
            "CRUD + UI alone is cosmetic. LLMs gravitate toward surface-level implementation and miss deep integration."
        ),
    },
    {
        "id": "M-16",
        "category": "backend,migration,consumers",
        "content": (
            "M-16 BACKEND: Update ALL consumers when migrating to a new system. "
            "When auth profiles replace env vars, grep for every reference to the old access pattern and update it. "
            "Orphaned consumers show stale data forever. "
            "A grep for the old pattern should be part of every migration checklist."
        ),
    },
    {
        "id": "M-17",
        "category": "feature,redundancy,audit",
        "content": (
            "M-17 REDUNDANCY: Audit existing tools before building new ones. "
            "Before implementing any new capability, grep the codebase for existing tools that do the same thing. "
            "If overlap exists, extend the existing tool. "
            "Ghost had a mature native Playwright browser tool but the LLM built a second inferior duplicate. "
            "A capability audit step should precede every feature implementation."
        ),
    },
    {
        "id": "M-18",
        "category": "dependency,runtime,validation",
        "content": (
            "M-18 DEPENDENCY: Validate runtime dependencies, not just imports. "
            "evolve_test checks Python syntax and imports but not system-level prerequisites. "
            "If code uses Playwright, verify browser binaries are installed. "
            "If it uses an external service, verify the service is reachable. "
            "Deploy succeeded but failed at runtime with 'browser binaries not found'."
        ),
    },
    {
        "id": "M-19",
        "category": "evolution,scope,single-responsibility",
        "content": (
            "M-19 EVOLUTION: Single-responsibility evolutions only. "
            "One evolution = one feature. Do not try to add chat interrupt endpoints AND improve evolve_test simultaneously. "
            "Multi-scope evolutions lead to 50-step, error-riddled, token-wasting processes. "
            "If you encounter a bug during implementation, fix it in the same evolution only if it directly blocks your feature."
        ),
    },
    {
        "id": "M-20",
        "category": "evolution,testing,gate",
        "content": (
            "M-20 EVOLUTION: Test failures are a hard gate — max 5 retries then auto-rollback. "
            "Do not keep retrying evolve_test indefinitely. After 5 failures, the evolution auto-rollbacks. "
            "During several evolution cycles, test failures were reported but Ghost continued and sometimes deployed anyway. "
            "Diagnose the root cause efficiently instead of brute-force retrying."
        ),
    },
    {
        "id": "M-21",
        "category": "evolution,deploy,verification",
        "content": (
            "M-21 EVOLUTION: Always verify after deploy — post-deploy smoke tests are mandatory. "
            "After evolve_deploy, the feature must actually work. Hit new API endpoints with web_fetch. "
            "Check that status endpoints return live data, not stale defaults. "
            "Features deployed in broken states (Projects modal always open, status endpoints returning stale data) "
            "because Ghost considered them 'done' without verification."
        ),
    },
    {
        "id": "M-22",
        "category": "evolution,testing,auditor",
        "content": (
            "M-22 AUDITING: Functional assertions, not just existence checks. "
            "'API returns 200' is necessary but not sufficient — the response body must contain correct live data. "
            "A status endpoint that always returns {running: false} regardless of reality is BROKEN even with HTTP 200. "
            "The Implementation Auditor checked routes returned 200 and files existed, but didn't verify actual functionality."
        ),
    },
    {
        "id": "M-23",
        "category": "evolution,feature,atomic",
        "content": (
            "M-23 FEATURE: Backend + Frontend = one atomic feature. "
            "Never deploy a backend without its corresponding dashboard UI, or vice versa. "
            "Ghost implemented full Projects CRUD backend but never created the dashboard page. "
            "Backend + Frontend should be treated as a single atomic feature, not two independent features."
        ),
    },
]


def seed():
    db = MemoryDB()
    seeded = 0
    skipped = 0
    for m in MISTAKES:
        if db.has_source(m["id"]):
            skipped += 1
            continue
        db.save(
            content=m["content"],
            type="mistake",
            tags=m["category"],
            source_preview=m["id"],
            source_hash=m["id"],
        )
        seeded += 1
    db.close()
    print(f"Seeded {seeded} mistakes into memory DB ({skipped} already existed)")


if __name__ == "__main__":
    seed()
